services:
  db:
    image: postgres:alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dumbbank
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - cache:/data

volumes:
  db:
  cache: